server:
  port: 8080

spring:
  profiles:
    active: dev
  sql:
    init:
      mode: never
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

log:
  http:
    enabled: true
    body-enabled: true
    max-body-length: 5000

springdoc:
  writer-with-order-by-keys: true
  paths-to-exclude:
    - /hello
    - /user/**
