server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kg_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

log:
  http:
    enabled: true
    body-enabled: true
    max-body-length: 5000

springdoc:
  writer-with-order-by-keys: true
  paths-to-exclude:
    - /hello
    - /user/**
